config/routes.rb
RailsRacer::Application.routes.draw do
  
  resources :sessions, only: [:create, :destroy]

  delete '/logout' => "sessions#destroy", :as => 'logout'

  root :to => 'pages#main'

  resources :users
  resources :games do
    member do
      put 'move'
      post 'results'
      get 'waiting'
    end
  end

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :p1_position, :p2_position, :winner_id, :game_time

  has_many :game_users
  has_many :users, :through => :game_users

  validates :p1_position, :presence => true
  validates :p2_position, :presence => true


  def advance!(game_user)
    p game_user
    if game_user.player == 1
      self.update_attributes(p1_position: self.p1_position + 1) 
    else 
      self.update_attributes(p2_position: self.p2_position + 1)
    end
  end

  def locate_game_user(user_id)
    GameUser.where(:user_id => user_id,
                   :game_id => self.id).first
  end

  def finish!(winner, game_time, position)
    self.update_attributes(winner_id: winner[:id], 
                           game_time: game_time,
                           p1_position: position[:player1],
                           p2_position: position[:player2] )
  end

  def player2
    user_id = self.game_users.where(:player => 2).first.user_id
    user = User.find(user_id)
  end

  def player1
    user_id = self.game_users.where(:player => 1).first.user_id
    user = User.find(user_id)
  end

  def winner
    User.find(self.winner_id)
  end

  def loser
    loser = self.game_users.where("user_id != ?", self.winner_id).first
    User.find(loser.user_id)
  end

  def open?
    self.game_users.length < 2
  end

  def winning_margin
    (p1_position - p2_position).abs
  end
  


end

app/models/game_user.rb
class GameUser < ActiveRecord::Base
  attr_accessible :user_id, :game_id, :player

  belongs_to :game
  belongs_to :user

  validates :game_id, :user_id, :presence => true

  validates_uniqueness_of :game_id, :scope => [:user_id]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :remember_token
  has_secure_password

  has_many :games, :through => :game_users
  has_many :game_users

  validates :name,  :presence => true
  validates :email, :presence => true, :uniqueness => true

  def games_won
    self.games.where(:winner_id => self.id)
  end

  def games_lost
    self.games.where("winner_id != ?", self.id)
  end

  def average_game_time
    self.games.average('game_time')
  end

  def won_last_game?
    self.games.last.winner_id == self.id
  end

  def average_winning_margin
    winning_margin.to_f / self.games_won.length.to_f
  end

   def average_losing_margin
    losing_margin.to_f / self.games_lost.length.to_f
  end

  def average_total_margin
    total_margin.to_f / self.games.length.to_f 
  end

  def winning_margin
    self.games_won.inject(0) { |sum, game| sum += game.winning_margin.to_i }
  end

  def losing_margin
    self.games_lost.inject(0) { |difference, game| difference -= game.winning_margin.to_i }
  end

  def total_margin
    self.winning_margin + self.losing_margin
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def index
    @open_games = Game.all.select { |game| game.open? }
  end

  def new
    @game = Game.new
  end

  def create
    @user1 = User.find(session[:user_id])
    @game = Game.create 
    @user1.games << @game
    game_user = GameUser.find_by_game_id_and_user_id(@game.id, @user1.id)
    game_user.update_attributes(player: 1)
    @game.save!
    redirect_to @game
  end

  def update 
    # create a new game_user 
  end 

  def move
    game = Game.find(params[:id])
    game_user = game.locate_game_user(params[:user_id])
    game.advance!(game_user)
    render json: { p1_position: game.p1_position, p2_position: game.p2_position, p2_id: game.player2.id }
  end

  def show
    @game = Game.find(params[:id])
    @user1 = @game.users.first 
    unless @user1 == current_user
      @user2 = current_user 
      @user2.games << @game
      game_user = GameUser.find_by_game_id_and_user_id(@game.id, @user2.id)
      game_user.update_attributes(player: 2)
    end
  end

  def results
    @game = Game.find(params[:id])
    @game.finish!(params[:winner],params[:game_time], params[:position])
    redirect_to user_path(current_user)
  end 

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def main
    puts session.inspect
    @user = User.new
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "Welcome back, #{@user.name}!"
      redirect_to new_game_path
    else
      flash[:error] = 'Inccorect email/password combination.'
      redirect_to root_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "User successfully created"
      redirect_to new_game_path
    else
      render 'pages/main'
    end
  end

  def show
    puts 'YYYYY'
    puts flash.inspect
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end
  end
end

app/helpers/game_helper.rb
module GameHelper

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/games/create.html.erb
<h1>Game#create</h1>
<p>Find me in app/views/game/create.html.erb</p>

app/views/games/index.html.erb
<h3>Create Game</h3>
<%= link_to 'Create Game!', new_game_path %>

<h3>Join Open Game!</h3>
<% @open_games.each do |game| %>
  <%= link_to game.id, game_path(game) %>
<% end %>

app/views/games/new.html.erb
<%= form_for @game do |f| %>
  <% f.submit "Create Game!" %>
<% end %>

app/views/games/show.html.erb
<div class='game' data-game-id="<%= @game.id %>"></div>
<div class='current_user' data-current-user-id="<%= current_user.id%>"></div>
<span data-player1-id="<%= @user1.id %>"></span>
<p data-player2-id="<%= @user2 && @user2.id %>"></p>

<% if current_user.id == @user1.id %>
  <%= "You're Player1. Press 'q' to move!" %>
<% else %>
  <%= "You're Player2.  Press 'p' to move!" %>
<% end %>


<table>
  <tr class='player1-board'>
    <% 10.times do |n| %>
      <td><%= n %></td> 
    <% end %>
  </tr>

  <tr class="blank_row">
    <td colspan="3"></td>
  </tr>

  <tr class='player2-board'>
    <% 10.times do |n| %>
      <td><%= n %></td> 
    <% end %>
  </tr> 
</table>

<script type="text/javascript">

function Player(id) {
  this.id       = id;
  this.position = 1;
}

Player.prototype.advance = function() {
  this.position ++;
};

function Game(player1, player2, id) {
  this.player1    = player1;
  this.player2    = player2;
  this.player2Id  = null;
  this.startTime  = $.now();
  this.boardSize  = 10;
  this.gameTime   = null;
  this.winner     = null;
  this.loser      = null;
  this.id         = id;
}

Game.prototype.finished = function() {
  if(game.player1.position == game.boardSize || game.player2.position == game.boardSize){
    game.gameTime = game.startTime - $.now();
    return true;
  } else {
    return false;
  }
}

Game.prototype.updateBoard = function() {
  $("td").removeClass("active");
  $(".player1-board td:nth-child(" +player1.position+ ")").addClass("active");
  $(".player2-board td:nth-child(" +player2.position+ ")").addClass("active");
}

Game.prototype.onKeyUp = function(event) {
  if (game.finished() == true){
    $(location).attr('href', '/users/' + $('.current_user').attr('data-current-user-id'))
  } else {
    if(event.keyCode == 81){
      player1.advance();
      $.ajax({
        url: '/games/'+ game.id +'/move',
        type: 'PUT',
        data: {user_id: player1.id},
        success: function(data) {
          player1.position = data.p1_position;
          player2.position = data.p2_position;
          player2.id       = data.p2_id;
          game.updateBoard();
        }
      });
      game.updateBoard();
      if(game.finished() == true){
        game.winner = player1;
        game.loser  = player2;
        $.ajax({
          url: '/games/' + game.id + '/results',
          type: 'POST',
          data: {game_time: game.gameTime, winner: game.winner, loser:  game.loser, position: {player1: game.player1.position, player2: game.player2.position}},
          success: function(data) {
            $(location).attr('href', '/users/' + $('.current_user').attr('data-current-user-id'))
          }
        });
      }
    }
    else if(event.keyCode == 80){
      player2.advance();
      $.ajax({
        url: '/games/'+ game.id +'/move',
        type: 'PUT',
        data: {user_id: player2.id},
        success: function(data) {
          player1.position = data.p1_position;
          player2.position = data.p2_position;
          player2.id       = data.p2_id;
          game.updateBoard();
        }
      });
      game.updateBoard();
      if(game.finished() == true){
        game.winner = player2;
        game.loser  = player1;
        $.ajax({
          url: '/games/' + game.id + '/results',
          type: 'POST',
          data: {game_time: game.gameTime, winner: game.winner, loser:  game.loser, position: {player1: game.player1.position, player2: game.player2.position}},
          success: function(data) {
            $(location).attr('href', '/users/' + $('.current_user').attr('data-current-user-id'))
          }
        });
      }
    }
  }  
}

jQuery(document).ready(function($) {
  var gameId = $('.game').attr('data-game-id');
  var p1Id = $("span").attr("data-player1-id"); 
  var p2Id = $("p").attr("data-player2-id"); 
  var currentUserId = $('.current_user').attr('data-current-user-id');
  player1 = new Player(p1Id);
  player2 = new Player(p2Id);
  game = new Game(player1, player2, gameId);
  game.updateBoard();
  $(document).on('keyup', game.onKeyUp);
});


// Place all the behaviors and hooks related to the matching controller here.
// All this logic will automatically be available in application.js.
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRacer</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <link href='http://fonts.googleapis.com/css?family=Faster+One' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Rokkitt' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="nav">
    <% if current_user %>
      <%= link_to 'Home', root_path %>
      <%= link_to 'Browse Games', games_path %>
      <%= link_to 'My Profile', user_path(current_user) %>
      <%= link_to 'Log Out', logout_path, :method => 'delete' %>
    <% end %>
    </header>
    <div class='text-error'>
      <% if flash[:error] %>
        <%= flash[:error] %>
      <% end %>
    </div>
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
    <% end %>
    <div class='notice'>
        <%= flash[:notice] %>
    </div>
    <div class='success'>
      <% if flash[:success] %>
        <%= flash[:success] %>
      <% end %>
    </div>
  <%= yield %>
  </body>
</html>

app/views/pages/main.html.erb
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h1>Welcome to <span class='title'>Rails Racer</span></h1>

<div class="new-user-form">
  <%= form_for @user do |f| %>
    <%= f.text_field :name, :placeholder => 'Name' %> 
    <%= f.email_field :email, :placeholder => 'Email' %>
    <%= f.password_field :password, :placeholder => 'Password' %>
    <%= f.password_field :password_confirmation, :placeholder => 'Confirm Password' %>
    <%= f.submit 'Sign up', :class => 'btn btn-primary' %>
  <% end %> 

  <%= form_for(:session, url: sessions_path) do |f| %>
    <%= f.email_field :email, :placeholder => 'Email' %>
    <%= f.password_field :password, :placeholder => 'Password' %>
    <%= f.submit 'Sign in', :class => 'btn btn-primary' %> 
  <% end %> 
</div>

<%= image_tag 'rails_racer.jpg', :id => "main-picture" %>

app/views/users/show.html.erb
<%= @user.name %>'s Ruby Racer Profile

<% if @user.won_last_game? %>
  <div class='winner'>
    <h4>You won your last game!</h4>
  </div>
<% else %>
  <div class='loser'>
    <h4>You lost your last game.</h4>
  </div>
<% end %>

<% if @user.games.empty? %>
  <h2>No Games played. <%=link_to 'Play a Game!', games_path %></h2>
<% else %>
  <h2>Your Win Percentage: <%= ((@user.games_won.length.to_f / @user.games.length.to_f) * 100).round(2) %>%  <%# write methods to abstract from views %>
  <h2>Your Average Gameplay time: <%= ((@user.games_won.average('game_time')).to_f / 1000).abs.round(2) %> seconds</h2>
  <h2>Your Fastest Game Time: <%= (@user.games_won.maximum('game_time').to_f / 1000).abs.round(2) %> seconds </h2>
  
  <h2>Your average winning margin:<%= @user.average_winning_margin %></h2>
  <h2>Your average losing margin:<%= @user.average_losing_margin %></h2>
  <h2>Your average total margin:<%= @user.average_total_margin %></h2>

<% end %>